"""try new path

Revision ID: 1a63f72cc7fe
Revises: b65b7ee12116
Create Date: 2020-05-09 23:58:28.905234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a63f72cc7fe'
down_revision = 'b65b7ee12116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
