"""empty message

Revision ID: 5eb629904e59
Revises: 1a63f72cc7fe
Create Date: 2020-05-10 00:10:02.462058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb629904e59'
down_revision = '1a63f72cc7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
