"""uptodate

Revision ID: b18aa9eb6208
Revises: c669cf846f40
Create Date: 2020-05-10 15:06:34.982056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18aa9eb6208'
down_revision = 'c669cf846f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
