"""uptodate

Revision ID: b89c93d6312a
Revises: b18aa9eb6208
Create Date: 2020-05-10 15:25:46.216151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89c93d6312a'
down_revision = 'b18aa9eb6208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
