"""uptodate

Revision ID: c669cf846f40
Revises: 5eb629904e59
Create Date: 2020-05-10 15:05:05.348603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c669cf846f40'
down_revision = '5eb629904e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
