"""yolo

Revision ID: e47906fa1c7b
Revises: b89c93d6312a
Create Date: 2020-05-10 19:55:40.405742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47906fa1c7b'
down_revision = 'b89c93d6312a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
